//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISharedMemory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int idProduit { get; set; }
        public string codeProduit { get; set; }
        public string designationProduit { get; set; }
        public Nullable<int> PU { get; set; }
        public Nullable<int> QteMin { get; set; }
        public Nullable<int> QteCri { get; set; }
        public string codeCategorie { get; set; }
    }
}
