//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public int idUtilisateur { get; set; }
        public string identifiantUtilisateur { get; set; }
        public string motDePasse { get; set; }
        public string codeProfil { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string ChangerMotDePasse { get; set; }
    }
}
